
//! Autogenerated weights for pb
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 3.0.0
//! DATE: 2021-04-20, STEPS: [50, ], REPEAT: 20, LOW RANGE: [], HIGH RANGE: []
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 128

// Executed Command:
// target/release/antimatter-network
// benchmark
// --dev
// --steps
// 50
// --repeat
// 20
// --pallet
// pb
// --extrinsic
// *
// --execution
// wasm
// --wasm-execution
// compiled
// --output=./runtime/src/weights/


#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for pb.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pb::WeightInfo for WeightInfo<T> {
	fn adjust_deposit() -> Weight {
		(351_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(8 as Weight))
			.saturating_add(T::DbWeight::get().writes(8 as Weight))
	}
	fn adjust_debit() -> Weight {
		(389_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(6 as Weight))
			.saturating_add(T::DbWeight::get().writes(6 as Weight))
	}
}
